# Boost Software License - Version 1.0 - August 17th, 2003
#
# Permission is hereby granted, free of charge, to any person or organization
# obtaining a copy of the software and accompanying documentation covered by
# this license (the "Software") to use, reproduce, display, distribute,
# execute, and transmit the Software, and to prepare derivative works of the
# Software, and to permit third-parties to whom the Software is furnished to
# do so, all subject to the following:
#
# The copyright notices in the Software and this entire statement, including
# the above license grant, this restriction and the following disclaimer,
# must be included in all copies of the Software, in whole or in part, and
# all derivative works of the Software, unless such copies or derivative
# works are solely in the form of machine-executable object code generated by
# a source language processor.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
# SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
# FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
# ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
# DEALINGS IN THE SOFTWARE.

import clang
import check_name
from mock import MagicMock, patch
import pytest


def test_analysis_will_set_llvm_path(tester):
    tester.with_llvm_path('path')
    tester.test()
    tester.configuration.set_library_path.assert_called_once_with('path')


def test_analysis_will_create_clang_index(tester):
    tester.test()
    tester.index_class.create.assert_called_once_with()


def test_analysis_will_pass_target_file_to_clang(tester):
    tester.with_target_path('target').test()
    tester.index.parse.assert_called_once_with('target', [])


def test_analysis_will_pass_unknown_options_to_clang(tester):
    tester.with_target_path('t').with_additional_option('option', '1').test()
    tester.index.parse.assert_called_once_with('t', ['--option', '1'])


def test_analysis_is_done(tester):
    tester.test()
    tester.analyzer.assert_called_once_with(tester.output, 'TranslationUnit')


def test_missing_source_file_is_an_error(tester):
    assert 0 != tester.with_missing_target_path().test()


def test_missing_source_file_is_reported(tester):
    tester.with_missing_target_path().test()
    expected = str(clang.cindex.TranslationUnitLoadError())
    tester.output.error.assert_called_once_with(expected)


def test_errors_are_noticed(tester):
    assert 0 != tester.with_errors().test()


def test_success_noticed(tester):
    assert 0 == tester.without_errors().test()


@pytest.fixture
def tester(request):
    result = _Tester()
    request.addfinalizer(patch.stopall)
    return result


class _Tester:
    def __init__(self):
        self.llvm_path = 'llvm_path'
        self.target_path = 'target_path'
        self.extra_arguments = []

        self.configuration = self._add_patch_without_autospec(
            'clang.cindex.conf')

        self.index_class = self._add_patch('clang.cindex.Index')
        self.index_class.create.return_value = self.index = MagicMock()
        self.index.parse.return_value = 'TranslationUnit'
        self.index_class.return_value = self.index

        self.analyzer = self._add_patch('analyze.analyze_translation_unit')

        self.output_creator = self._add_patch('report.Output')
        self.output = MagicMock()
        self.output_creator.return_value = self.output

        self.without_errors()

    def with_llvm_path(self, path):
        self.llvm_path = path
        return self

    def with_additional_option(self, name, value):
        self.extra_arguments += _option_as_list(name, value)
        return self

    def with_missing_target_path(self):
        exception = clang.cindex.TranslationUnitLoadError()
        self.index.parse.side_effect = exception
        return self

    def without_errors(self):
        self.output.has_errors = False
        return self

    def with_errors(self):
        self.output.has_errors = True
        return self

    def with_target_path(self, path):
        self.target_path = path
        return self

    def test(self):
        return check_name.main(self._build_argument_list())

    def _build_argument_list(self):
        arguments = ['executable']
        arguments += _option_as_list('llvm_path', self.llvm_path)
        arguments += _option_as_list('target', self.target_path)
        arguments += self.extra_arguments
        return arguments

    def _add_patch(self, name):
        patcher = patch(name, autospec=True)
        return patcher.start()

    def _add_patch_without_autospec(self, name):
        patcher = patch(name, autospec=False)
        return patcher.start()


def _option_as_list(name, value):
    if not value:
        return []
    return ['--' + name, value]
